"""Generate the retained-backup manifest for gitignored retained evidence.

`experiments/results/*.json` is gitignored yet permanently retained
(ADR-0477), so branch pushes cannot protect it. This manifest binds every
such file to its byte length, raw SHA-256, and the capture that carries it
off-machine (for example a GitHub release tag). The retained-evidence
inventory test enforces the manifest: an on-disk retained file that is
neither tracked nor captured fails closed, and a captured file whose bytes
drift or disappear fails closed.

`--check` verifies the manifest matches the directory; `--write` regenerates
it, preserving each unchanged file's original capture label and requiring
`--capture <label>` whenever a new or changed file must be admitted.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import subprocess
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "experiments" / "results"
MANIFEST = ROOT / "docs" / "architecture" / "retained-backup-manifest.toml"
MAXIMUM_BYTES = 1024 * 1024 * 1024


class ManifestError(ValueError):
    pass


def _read_bounded(path: Path) -> bytes:
    info = os.stat(path, follow_symlinks=False)
    if not os.path.isfile(path):
        raise ManifestError(f"retained path is not a regular file: {path}")
    if int(info.st_size) > MAXIMUM_BYTES:
        raise ManifestError(f"retained file exceeds the bounded read: {path}")
    with open(path, "rb") as handle:
        raw = handle.read(MAXIMUM_BYTES + 1)
    if len(raw) != int(info.st_size):
        raise ManifestError(f"retained file changed while reading: {path}")
    return raw


def _tracked_result_paths() -> frozenset[str]:
    executable = os.environ.get("PONTIUS_GIT")
    if type(executable) is not str or not Path(executable).is_absolute():
        raise ManifestError("PONTIUS_GIT must name an absolute executable")
    completed = subprocess.run(
        [executable, "-C", str(ROOT), "ls-files", "-z", "--", "experiments/results"],
        capture_output=True,
        check=True,
    )
    rows = completed.stdout.decode("utf-8", "surrogateescape").split("\0")
    return frozenset(row for row in rows if row)


def _scan() -> list[dict[str, object]]:
    if not RESULTS.is_dir():
        raise ManifestError("experiments/results is absent")
    tracked = _tracked_result_paths()
    rows: list[dict[str, object]] = []
    for entry in sorted(RESULTS.iterdir(), key=lambda item: item.name):
        if not entry.is_file() or entry.name == ".gitkeep":
            continue
        if f"experiments/results/{entry.name}" in tracked:
            # Tracked retained files ride the remote through git; the
            # manifest binds only the gitignored loose population, whose
            # bytes never pass through checkout conversion.
            continue
        raw = _read_bounded(entry)
        rows.append(
            {
                "relative_path": f"experiments/results/{entry.name}",
                "byte_length": len(raw),
                "raw_sha256": hashlib.sha256(raw).hexdigest(),
            }
        )
    return rows


def load_manifest() -> dict[str, dict[str, object]]:
    raw = _read_bounded(MANIFEST)
    document = tomllib.loads(raw.decode("utf-8"))
    files = document.get("files")
    if type(files) is not list:
        raise ManifestError("manifest files table is absent")
    entries: dict[str, dict[str, object]] = {}
    for row in files:
        if type(row) is not dict:
            raise ManifestError("manifest row is not a table")
        path = row.get("relative_path")
        length = row.get("byte_length")
        digest = row.get("raw_sha256")
        capture = row.get("capture")
        if (
            type(path) is not str
            or type(length) is not int
            or isinstance(length, bool)
            or type(digest) is not str
            or len(digest) != 64
            or type(capture) is not str
            or not capture
        ):
            raise ManifestError(f"manifest row is not exactly typed: {row!r}")
        if path in entries:
            raise ManifestError(f"manifest repeats a path: {path}")
        entries[path] = {
            "relative_path": path,
            "byte_length": length,
            "raw_sha256": digest,
            "capture": capture,
        }
    return entries


def _render(rows: list[dict[str, object]]) -> bytes:
    lines = [
        "# Retained-backup manifest: gitignored retained evidence bound to its",
        "# off-machine capture. Generated by",
        "# tools/generate_retained_backup_manifest.py; regenerate with --write",
        "# and an explicit --capture label after every new backup capture.",
        "",
        f"schema_version = \"pontius-retained-backup-v1\"",
        "",
    ]
    for row in rows:
        lines.extend(
            [
                "[[files]]",
                f"relative_path = \"{row['relative_path']}\"",
                f"byte_length = {row['byte_length']}",
                f"raw_sha256 = \"{row['raw_sha256']}\"",
                f"capture = \"{row['capture']}\"",
                "",
            ]
        )
    return ("\n".join(lines).rstrip("\n") + "\n").encode("ascii")


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    parser.add_argument("--capture", default=None)
    arguments = parser.parse_args()

    scanned = _scan()
    previous: dict[str, dict[str, object]] = {}
    if MANIFEST.is_file():
        previous = load_manifest()

    rows: list[dict[str, object]] = []
    admitted: list[str] = []
    for row in scanned:
        path = str(row["relative_path"])
        prior = previous.get(path)
        if (
            prior is not None
            and prior["byte_length"] == row["byte_length"]
            and prior["raw_sha256"] == row["raw_sha256"]
        ):
            row["capture"] = prior["capture"]
        else:
            if arguments.capture is None:
                raise ManifestError(
                    "new or changed retained file requires an explicit "
                    f"--capture label: {path}"
                )
            row["capture"] = arguments.capture
            admitted.append(path)
        rows.append(row)

    tracked = _tracked_result_paths()
    removed = sorted(set(previous) - {str(row["relative_path"]) for row in rows})
    lost = [path for path in removed if path not in tracked]
    if lost:
        raise ManifestError(
            "retained files are absent from disk (retained evidence is never "
            "deleted): " + ", ".join(lost)
        )

    rendered = _render(rows)
    if arguments.check:
        if not MANIFEST.is_file() or _read_bounded(MANIFEST) != rendered:
            raise ManifestError(
                "retained-backup manifest is stale; run --write with a "
                "--capture label for any new capture"
            )
        print(f"retained-backup manifest is current ({len(rows)} files)")
        return 0
    MANIFEST.write_bytes(rendered)
    print(
        f"wrote {MANIFEST} ({len(rows)} files, {len(admitted)} newly admitted)"
    )
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except ManifestError as error:
        print(f"retained-backup manifest failed: {error}", file=sys.stderr)
        raise SystemExit(2)
