"""Generate the repository front door from durable ADR metadata."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
import hashlib
from pathlib import Path
import re


_ROOT = Path(__file__).parents[2]
_DECISIONS = _ROOT / "docs/decisions"
_OUTPUT = _ROOT / "STATUS.md"
_TITLE = re.compile(r"^# ADR-(\d+):\s+(.+?)\s*$")
_FIELD = re.compile(r"^-?\s*\*{0,2}(Status|Date):\*{0,2}\s*(.+?)\s*$", re.IGNORECASE)


@dataclass(frozen=True, slots=True)
class DecisionHeader:
    number: int
    title: str
    status: str
    date: str
    path: Path
    decision: str


def _section(lines: list[str], heading: str) -> str:
    target = f"## {heading}".lower()
    start = next((index + 1 for index, line in enumerate(lines) if line.strip().lower() == target), None)
    if start is None:
        return ""
    end = next((index for index in range(start, len(lines)) if lines[index].startswith("## ")), len(lines))
    return "\n".join(lines[start:end]).strip()


def _section_first_line(lines: list[str], heading: str) -> str:
    body = _section(lines, heading)
    return next((line.strip() for line in body.splitlines() if line.strip()), "")


def read_decision_headers(decisions_dir: Path = _DECISIONS) -> tuple[DecisionHeader, ...]:
    """Read every numbered ADR and its durable decision metadata."""

    rows = []
    for path in decisions_dir.glob("ADR-*.md"):
        lines = path.read_text(encoding="utf-8").splitlines()
        title_match = next((_TITLE.match(line) for line in lines if _TITLE.match(line)), None)
        if title_match is None:
            raise ValueError(f"decision lacks a canonical ADR title: {path}")
        fields: dict[str, str] = {}
        for line in lines[:20]:
            match = _FIELD.match(line)
            if match is not None:
                fields[match.group(1).lower()] = match.group(2).strip()
        status = fields.get("status") or _section_first_line(lines, "Status") or "unspecified"
        date = fields.get("date", "")
        rows.append(
            DecisionHeader(
                number=int(title_match.group(1)),
                title=title_match.group(2).strip(),
                status=status,
                date=date,
                path=path,
                decision=_section(lines, "Decision"),
            )
        )
    rows.sort(key=lambda row: row.number)
    if not rows or len({row.number for row in rows}) != len(rows):
        raise ValueError("decision numbers must be nonempty and unique")
    return tuple(rows)


def _is_preregistration(row: DecisionHeader) -> bool:
    text = f"{row.title} {row.status}".lower()
    return "preregister" in text or "preregistration" in text


def _is_process(row: DecisionHeader) -> bool:
    return "process" in row.status.lower()


def _link(row: DecisionHeader, root: Path) -> str:
    relative = row.path.relative_to(root).as_posix()
    return f"[ADR-{row.number:04d}]({relative})"


def _header_digest(rows: tuple[DecisionHeader, ...], root: Path) -> str:
    payload = "\n".join(
        f"{row.number}|{row.title}|{row.status}|{row.date}|{row.path.relative_to(root).as_posix()}"
        for row in rows
    )
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def render_status(root: Path = _ROOT, *, recent_count: int = 24) -> str:
    """Render a compact current status whose freshness is testable."""

    rows = read_decision_headers(root / "docs/decisions")
    latest = rows[-1]
    research_rows = tuple(
        row
        for row in rows
        if not _is_preregistration(row)
        and not _is_process(row)
        and "accepted" in row.status.lower()
    )
    process_rows = tuple(row for row in rows if _is_process(row))
    prereg_rows = tuple(row for row in rows if _is_preregistration(row))
    if not research_rows:
        raise ValueError("status generation requires an accepted research decision")
    research = research_rows[-1]
    process = process_rows[-1] if process_rows else None
    newest_prereg = prereg_rows[-1] if prereg_rows else None
    open_prereg = newest_prereg if newest_prereg is not None and newest_prereg.number > research.number else None
    digest = _header_digest(rows, root)

    lines = [
        "# Project Status",
        "",
        "> Generated by `python -m pontius.status_generation` from ADR metadata.",
        "> Do not edit this file by hand; `test_status_generation` enforces freshness.",
        "",
        "## Active checkpoint",
        "",
        f"Latest accepted research result: {_link(research, root)} — {research.title}.",
        "",
        f"Status: {research.status}.",
        "",
        "## Current decision",
        "",
    ]
    lines.extend((research.decision or "The latest research ADR has no explicit Decision section.").splitlines())
    lines.extend(["", "## Open preregistration", ""])
    if open_prereg is None:
        lines.append("None. The latest preregistration has a newer research result.")
    else:
        lines.append(f"{_link(open_prereg, root)} — {open_prereg.title} ({open_prereg.status}).")
    lines.extend(["", "## Evidence protocol", ""])
    if process is None:
        lines.append("See [PROJECT.md](PROJECT.md).")
    else:
        lines.append(f"Latest process decision: {_link(process, root)} — {process.title}.")
        lines.append("")
        lines.append("Canonical rules: [PROJECT.md](PROJECT.md#evidence-and-dissent-protocol).")
    lines.extend(
        [
            "",
            "## Recent decision ledger",
            "",
            "| ADR | Date | Status | Decision |",
            "|---:|---|---|---|",
        ]
    )
    for row in rows[-recent_count:]:
        lines.append(
            f"| {_link(row, root)} | {row.date or '—'} | {row.status} | {row.title} |"
        )
    lines.extend(
        [
            "",
            "## Repository snapshot",
            "",
            f"- Latest ADR: {_link(latest, root)} — {latest.title}.",
            f"- Numbered decisions: {len(rows)}.",
            f"- ADR-header SHA-256: `{digest}`.",
            "- Current blockers: none recorded by the latest accepted research decision.",
            "",
            "## Required reading before continuation",
            "",
            "1. [PROJECT.md](PROJECT.md)",
            "2. [STATUS.md](STATUS.md)",
            "3. [ROADMAP.md](ROADMAP.md)",
            f"4. {_link(research, root)} and its dependencies",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render_status()
    if args.check:
        if not _OUTPUT.is_file() or _OUTPUT.read_text(encoding="utf-8") != rendered:
            raise SystemExit("STATUS.md is stale; run python -m pontius.status_generation")
        print("STATUS.md is current")
        return
    _OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {_OUTPUT}")


if __name__ == "__main__":
    main()
